export const LIST_INVENTORY_REQUEST = 'LIST_INVENTORY_REQUEST';
export const LIST_INVENTORY_SUCCESS = 'LIST_INVENTORY_SUCCESS';
export const LIST_INVENTORY_FAIL = 'LIST_INVENTORY_FAIL';

export const LIST_ADD_REQUEST = 'LIST_ADD_REQUEST';
export const LIST_ADD_SUCCESS = 'LIST_ADD_SUCCESS';
export const LIST_ADD_FAIL = 'LIST_ADD_FAIL';

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAIL = 'GET_LIST_FAIL';

export const SAVE_LIST_REQUEST = 'SAVE_LIST_REQUEST';
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS';
export const SAVE_LIST_FAIL = 'SAVE_LIST_FAIL';

export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const TOGGLE_LIST_ITEM = 'TOGGLE_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
