export const LIST_INVENTORY_REQUEST = 'LIST_INVENTORY_REQUEST';
export const LIST_INVENTORY_SUCCESS = 'LIST_INVENTORY_SUCCESS';
export const LIST_INVENTORY_FAIL = 'LIST_INVENTORY_FAIL';

export const LIST_ADD_REQUEST = 'LIST_ADD_REQUEST';
export const LIST_ADD_SUCCESS = 'LIST_ADD_SUCCESS';
export const LIST_ADD_FAIL = 'LIST_ADD_FAIL';
